[package]
name = "musicxml-code-gen"
version = "0.1.0"
authors = ["Matt Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.2"
structopt = "0.3.11"
env_logger = "0.7.1"
log = "0.4.8"
exile = { version = "0.0.1", path = "/Users/mjb/repos/exile/exile" }