[package]
name = "musicxml-code-gen"
version = "0.1.0"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"

[dependencies]
exile = { version = "0.0.1", path = "/Users/mjb/repos/exile/exile" }
indexmap = "1.4.0"
structopt = "0.3.11"
tempfile = "3.1.0"
uuid = { version = "0.8", features = ["v4"] }